{{- if and .Values.radarr.enabled .Values.radarr.ingress.enabled .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "arr-stack.componentName" (dict "component" "radarr" "context" .) }}
  labels:
    {{- include "arr-stack.labels" . | nindent 4 }}
    {{- include "arr-stack.componentLabels" "radarr" | nindent 4 }}
  annotations:
    {{- with .Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    caddy.reverse_proxy: "http://{{ include "arr-stack.componentName" (dict "component" "radarr" "context" .) }}.{{ .Release.Namespace }}.svc.cluster.local:{{ .Values.radarr.service.port }}"
spec:
  {{- if .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  {{- if .Values.ingress.tls.enabled }}
  tls:
  - hosts:
    - {{ .Values.radarr.ingress.hostname }}.{{ .Values.ingress.domain }}
    {{- if .Values.ingress.tls.secretName }}
    secretName: {{ .Values.ingress.tls.secretName }}-radarr
    {{- end }}
  {{- end }}
  rules:
  - host: {{ .Values.radarr.ingress.hostname }}.{{ .Values.ingress.domain }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ include "arr-stack.componentName" (dict "component" "radarr" "context" .) }}
            port:
              number: {{ .Values.radarr.service.port }}
{{- end }}
